---
apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
name: commonthing-staging
networking:
  disableDefaultCNI: true
  kubeProxyMode: none
nodes:
  - role: control-plane
  - role: worker
    extraMounts:
      - hostPath: __COMMONTHING_STAGING_POSTGRES_ROOT__
        containerPath: /var/local/commonthing-staging/postgres
        readOnly: false
      - hostPath: __COMMONTHING_STAGING_NATS_ROOT__
        containerPath: /var/local/commonthing-staging/nats
        readOnly: false
  - role: worker
