---
apiVersion: v1
kind: Namespace
metadata:
  name: commonthing-experiment-b
  labels:
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
    # commonthing-naming: legacy
    weltgewebe.net/data-client: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: commonthing-data
  labels:
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
